language: node_js
sudo: required
branches:
  only:
    - master
cache: false
script: "npm run $TEST_SUITE"
env:
  - TEST_SUITE=lint
  - TEST_SUITE=jest
  - TEST_SUITE="wdio -- --suite suite1"
  - TEST_SUITE="wdio -- --suite suite2"
  - TEST_SUITE="wdio -- --suite suite3"
  - TEST_SUITE="wdio -- --suite suite4"
  - TEST_SUITE=danger
jobs:
  include:
    - stage: Deploy
      script: skip
      before_deploy:
        - npm run compile:prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: /build
        on:
          branch: master
